/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ShopsRequestBuilderNavigationMetadata, ShopsRequestBuilderRequestsMetadata, type ShopsRequestBuilder } from './shops/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The shops property
     */
    get shops(): ShopsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    shops: {
        requestsMetadata: ShopsRequestBuilderRequestsMetadata,
        navigationMetadata: ShopsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
