// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Mmp.Client.Identity.Manage.Info;
using Mmp.Client.Identity.Manage.Twofa;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mmp.Client.Identity.Manage
{
    /// <summary>
    /// Builds and executes requests for operations under \identity\manage
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ManageRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The info property</summary>
        public global::Mmp.Client.Identity.Manage.Info.InfoRequestBuilder Info
        {
            get => new global::Mmp.Client.Identity.Manage.Info.InfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Twofa property</summary>
        public global::Mmp.Client.Identity.Manage.Twofa.TwofaRequestBuilder Twofa
        {
            get => new global::Mmp.Client.Identity.Manage.Twofa.TwofaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mmp.Client.Identity.Manage.ManageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ManageRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identity/manage", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mmp.Client.Identity.Manage.ManageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ManageRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/identity/manage", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
